# samueldlh

# Configuration for Alacritty

env:
  # TERM variable
  TERM: alacritty
  LANG: "en_US.UTF-8"
  LC_CTYPE: en_US.UTF-8

window:

  # Window padding (changes require restart)
  padding:
   x: 9
   y: 7

  # Background opacity
  opacity: 0.9

# Font configuration
font:
  normal:

    normal:
      
      family: "JetBrainsMono NF"
      
      style: Regular

  # Point size
  size: 11.9