# samueldlh

# Configuration for Alacritty

window:

  # Window padding (changes require restart)
  padding:
   x: 9
   y: 7

  # Background opacity
  opacity: 0.9

# Font configuration
font:
  normal:

    normal:
      
      family: "JetBrainsMono NF"
      
      style: Regular

  # Point size
  size: 11.9